version: '3'
services:
  back:
    build: .
    # ECRからプルするためにECRのレジストリ情報を先頭につける
    # DockerHubからプルする場合はレジストリ情報は不要
    image: 025496840360.dkr.ecr.us-east-1.amazonaws.com/djnago-fb
    container_name: back
    
    environment:
      PRODUCTION: true
    ports:
        - "8010:8010"
    logging:
      # CloudWatch Logsにログを書き込む
      # FargateでECSを起動させるなら必須
      driver: awslogs
      options:
        awslogs-group: /ecs/
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs