version: '2'
services:
    nginx:
        image: nginx:1.13
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        depends_on:
            - back