# Generated by Django 3.2.3 on 2021-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210815_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_output3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_date', models.CharField(max_length=50)),
                ('kabu_name', models.CharField(max_length=50)),
                ('kabu_value', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='predict_output2',
        ),
    ]
