version: '2'
services:
    web:
        image: 025496840360.dkr.ecr.us-east-1.amazonaws.com/djnagouwsgi:latest
        command: 
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"