version: '2'
services:
    web:
        image: 025496840360.dkr.ecr.us-east-1.amazonaws.com/djnago_uwsgi:latest
        command: 
            uwsgi --socket :8001 --wsgi-file /Users/daisuke/my_port2/django2/drfapi/wsgi.py
        ports: 
            - "8001:8001"
        #depends_on:
        links:
            - db
    db:
        image: 025496840360.dkr.ecr.us-east-1.amazonaws.com/mysql:5.7    
        #restart: always
        #container_name: 
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: django-db
            MYSQL_USER: django
            MYSQL_PASSWORD: django
            TZ: 'Asia/Tokyo'
        tty: true
        ports:
            - 3306:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    nginx:
        image: nginx:1.13
        ports:
            - "80:80"
        volumes:
            - /Users/daisuke/my_port2/dockerfiles/django_docker2/nginx/conf:/etc/nginx/conf.d
            - /Users/daisuke/my_port2/dockerfiles/django_docker2/nginx/uwsgi_params:/etc/nginx/uwsgi_params
        #depends_on:
        links: 
          - web